
import java.awt.Color;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        jP_IniciarSesion.setVisible(false);
        jP_CrearCuenta.setVisible(false);
        jP_CrearUsuario.setVisible(false);
        jP_Concesionaria.setVisible(false);
        jP_Dentro.setVisible(false);
        jP_Garage.setVisible(false);
        jP_VentaCarros.setVisible(false);
        jL_Iniciar.setVisible(true);
        jB_login.setVisible(true);
        jB_crear.setVisible(true);
        
        //carrosAgrgar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jD_Menu = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu_modificar = new javax.swing.JMenu();
        jMenuItem_Marca = new javax.swing.JMenuItem();
        jMenuItem_Modelo = new javax.swing.JMenuItem();
        jMenuItem_year = new javax.swing.JMenuItem();
        jMenuItem_precio = new javax.swing.JMenuItem();
        jMenuItem_Eliminar = new javax.swing.JMenuItem();
        jP_Inicio = new javax.swing.JPanel();
        jB_crear = new javax.swing.JButton();
        jB_login = new javax.swing.JButton();
        jL_Iniciar = new javax.swing.JLabel();
        jP_IniciarSesion = new javax.swing.JPanel();
        jButton18 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPF_PasswordInicio = new javax.swing.JPasswordField();
        jTF_usuarioInicio = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jP_CrearCuenta = new javax.swing.JPanel();
        jButton19 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTF_nombre = new javax.swing.JTextField();
        jTF_correo = new javax.swing.JTextField();
        jTF_pais = new javax.swing.JTextField();
        jd_fecha = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jL_edad = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jP_CrearUsuario = new javax.swing.JPanel();
        jL_contra2 = new javax.swing.JLabel();
        jL_contra = new javax.swing.JLabel();
        jTF_usuario = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPF_Password = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jP_Dentro = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jP_Concesionaria = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jCB_Carros_pais = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jP_Garage = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListMejoras = new javax.swing.JList<>();
        jLabel17 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jP_VentaCarros = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        jPanel1.setBackground(new java.awt.Color(102, 255, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jD_MenuLayout = new javax.swing.GroupLayout(jD_Menu.getContentPane());
        jD_Menu.getContentPane().setLayout(jD_MenuLayout);
        jD_MenuLayout.setHorizontalGroup(
            jD_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jD_MenuLayout.setVerticalGroup(
            jD_MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu_modificar.setText("Modificar");
        jMenu_modificar.setToolTipText("");

        jMenuItem_Marca.setText("jMenuItem1");
        jMenu_modificar.add(jMenuItem_Marca);

        jMenuItem_Modelo.setText("jMenuItem1");
        jMenu_modificar.add(jMenuItem_Modelo);

        jMenuItem_year.setText("jMenuItem1");
        jMenu_modificar.add(jMenuItem_year);

        jMenuItem_precio.setText("jMenuItem1");
        jMenu_modificar.add(jMenuItem_precio);

        jPopupMenu1.add(jMenu_modificar);

        jMenuItem_Eliminar.setText("jMenuItem1");
        jPopupMenu1.add(jMenuItem_Eliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jP_Inicio.setBackground(new java.awt.Color(0, 0, 0));
        jP_Inicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jB_crear.setFont(new java.awt.Font("Five Nights at Freddy's", 0, 36)); // NOI18N
        jB_crear.setText("Crear una cuenta");
        jB_crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_crearMouseClicked(evt);
            }
        });
        jP_Inicio.add(jB_crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 220, 30));

        jB_login.setFont(new java.awt.Font("Five Nights at Freddy's", 0, 36)); // NOI18N
        jB_login.setText("Iniciar sesion");
        jB_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jB_loginMouseClicked(evt);
            }
        });
        jP_Inicio.add(jB_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 220, 30));

        jL_Iniciar.setFont(new java.awt.Font("Five Nights at Freddy's", 1, 40)); // NOI18N
        jL_Iniciar.setForeground(new java.awt.Color(255, 255, 255));
        jL_Iniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/650294(1).jpg"))); // NOI18N
        jP_Inicio.add(jL_Iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, -1));

        jP_IniciarSesion.setBackground(new java.awt.Color(0, 0, 0));
        jP_IniciarSesion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton18.setText("Volver Inicio");
        jButton18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton18MouseClicked(evt);
            }
        });
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jP_IniciarSesion.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jLabel14.setFont(new java.awt.Font("Five Nights at Freddy's", 0, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Usuario");
        jP_IniciarSesion.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, -1, -1));

        jLabel15.setFont(new java.awt.Font("Five Nights at Freddy's", 0, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Contrasena");
        jP_IniciarSesion.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, -1, -1));

        jPF_PasswordInicio.setFont(new java.awt.Font("Five Nights at Freddy's", 0, 36)); // NOI18N
        jPF_PasswordInicio.setForeground(new java.awt.Color(0, 0, 0));
        jP_IniciarSesion.add(jPF_PasswordInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 210, -1));

        jTF_usuarioInicio.setFont(new java.awt.Font("Five Nights at Freddy's", 0, 36)); // NOI18N
        jTF_usuarioInicio.setForeground(new java.awt.Color(0, 0, 0));
        jP_IniciarSesion.add(jTF_usuarioInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 210, -1));

        jButton7.setFont(new java.awt.Font("Five Nights at Freddy's", 0, 24)); // NOI18N
        jButton7.setText("Entrar");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        jP_IniciarSesion.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/need-for-speed-2560x1440-mclaren.jpg"))); // NOI18N
        jP_IniciarSesion.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jP_CrearCuenta.setBackground(new java.awt.Color(0, 0, 0));
        jP_CrearCuenta.setForeground(new java.awt.Color(255, 255, 255));
        jP_CrearCuenta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton19.setText("Volver Inicio");
        jButton19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton19MouseClicked(evt);
            }
        });
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jP_CrearCuenta.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Crear cuenta");
        jP_CrearCuenta.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Correo: ");
        jP_CrearCuenta.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre: ");
        jP_CrearCuenta.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Pais de residencia: ");
        jP_CrearCuenta.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha de nacimiento:");
        jP_CrearCuenta.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, -1, -1));

        jTF_nombre.setForeground(new java.awt.Color(0, 0, 0));
        jP_CrearCuenta.add(jTF_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 206, -1));

        jTF_correo.setForeground(new java.awt.Color(0, 0, 0));
        jP_CrearCuenta.add(jTF_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 206, -1));

        jTF_pais.setForeground(new java.awt.Color(0, 0, 0));
        jP_CrearCuenta.add(jTF_pais, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 206, -1));

        jd_fecha.setForeground(new java.awt.Color(255, 255, 255));
        jP_CrearCuenta.add(jd_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 206, -1));

        jButton1.setText("Crear Cuenta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jP_CrearCuenta.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, -1, -1));

        jL_edad.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jL_edad.setForeground(new java.awt.Color(255, 153, 153));
        jL_edad.setText("La edad debe ser mayor de 12.");
        jP_CrearCuenta.add(jL_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/652823(1).png"))); // NOI18N
        jP_CrearCuenta.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, -1));

        jP_CrearUsuario.setBackground(new java.awt.Color(0, 0, 0));
        jP_CrearUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jL_contra2.setFont(new java.awt.Font("Roboto", 3, 12)); // NOI18N
        jL_contra2.setForeground(new java.awt.Color(255, 102, 102));
        jL_contra2.setText("una minúscula y un carácter especial."); // NOI18N
        jP_CrearUsuario.add(jL_contra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, 210, -1));

        jL_contra.setFont(new java.awt.Font("Roboto", 3, 12)); // NOI18N
        jL_contra.setForeground(new java.awt.Color(255, 102, 102));
        jL_contra.setText("La contraseña debe tener una letra mayúscula,"); // NOI18N
        jP_CrearUsuario.add(jL_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 250, -1));

        jTF_usuario.setForeground(new java.awt.Color(0, 0, 0));
        jP_CrearUsuario.add(jTF_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 210, -1));

        jLabel9.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Crea tu cuenta");
        jP_CrearUsuario.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, -1, -1));
        jP_CrearUsuario.add(jPF_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 210, -1));

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Usuario: ");
        jP_CrearUsuario.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, -1, -1));

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Contraseña: ");
        jP_CrearUsuario.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, -1, -1));

        jButton2.setText("Crear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jP_CrearUsuario.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ford-Focus-RS-nfs-4k(1).jpg"))); // NOI18N
        jP_CrearUsuario.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jP_Dentro.setBackground(new java.awt.Color(0, 0, 0));
        jP_Dentro.setForeground(new java.awt.Color(0, 0, 0));
        jP_Dentro.setPreferredSize(new java.awt.Dimension(760, 470));
        jP_Dentro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setFont(new java.awt.Font("Five Nights at Freddy's", 0, 36)); // NOI18N
        jButton3.setText("Modificar Usuario");
        jP_Dentro.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, 50));

        jButton4.setFont(new java.awt.Font("Five Nights at Freddy's", 0, 36)); // NOI18N
        jButton4.setText("Garage");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jP_Dentro.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 226, 50));

        jButton5.setFont(new java.awt.Font("Five Nights at Freddy's", 0, 36)); // NOI18N
        jButton5.setText("Concesionaria");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jP_Dentro.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 226, 50));

        jButton6.setFont(new java.awt.Font("Five Nights at Freddy's", 0, 36)); // NOI18N
        jButton6.setText("Comprar Carro");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jP_Dentro.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 226, 50));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/650294(1).jpg"))); // NOI18N
        jP_Dentro.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, -1));

        jP_Concesionaria.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Marca", "Modelo", "Año", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Marca");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Modelo");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Año");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Precio");
        }

        jLabel12.setFont(new java.awt.Font("Five Nights at Freddy's", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText(" Carros Disponibles");

        jCB_Carros_pais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Japón", "USA", "Alemania", "Francia", "UK", "Suecia" }));
        jCB_Carros_pais.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCB_Carros_paisItemStateChanged(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Pais:");

        javax.swing.GroupLayout jP_ConcesionariaLayout = new javax.swing.GroupLayout(jP_Concesionaria);
        jP_Concesionaria.setLayout(jP_ConcesionariaLayout);
        jP_ConcesionariaLayout.setHorizontalGroup(
            jP_ConcesionariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_ConcesionariaLayout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(jP_ConcesionariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_ConcesionariaLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(264, 264, 264))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_ConcesionariaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_ConcesionariaLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCB_Carros_pais, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(229, 229, 229))))
        );
        jP_ConcesionariaLayout.setVerticalGroup(
            jP_ConcesionariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_ConcesionariaLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(33, 33, 33)
                .addGroup(jP_ConcesionariaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jCB_Carros_pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        jP_Garage.setBackground(new java.awt.Color(255, 255, 255));
        jP_Garage.setPreferredSize(new java.awt.Dimension(740, 470));
        jP_Garage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Marca", "Modelo", "Año de Fabricación", "Precio"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable2);

        jP_Garage.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 440, 280));

        jListMejoras.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(jListMejoras);

        jP_Garage.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 180, 200));

        jLabel17.setFont(new java.awt.Font("Five Nights at Freddy's", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Atributos");
        jP_Garage.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Japón", "USA", "Alemania", "Francia", "UK", "Suecia" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jP_Garage.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, 170, -1));

        jLabel18.setFont(new java.awt.Font("Five Nights at Freddy's", 0, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Carros en mi garage");
        jP_Garage.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        jP_VentaCarros.setBackground(new java.awt.Color(255, 255, 255));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout jP_VentaCarrosLayout = new javax.swing.GroupLayout(jP_VentaCarros);
        jP_VentaCarros.setLayout(jP_VentaCarrosLayout);
        jP_VentaCarrosLayout.setHorizontalGroup(
            jP_VentaCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_VentaCarrosLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(534, Short.MAX_VALUE))
        );
        jP_VentaCarrosLayout.setVerticalGroup(
            jP_VentaCarrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_VentaCarrosLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jP_Concesionaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jP_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jP_CrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jP_CrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jP_IniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jP_Dentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jP_Garage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jP_VentaCarros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jP_Concesionaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jP_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jP_CrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jP_CrearUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jP_IniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jP_Dentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jP_Garage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jP_VentaCarros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if (jTF_nombre.getText().isEmpty()|| jTF_correo.getText().isEmpty() || jTF_pais.getText().isEmpty() || jd_fecha.getDate()==null) {
            JOptionPane.showMessageDialog(this, "Llene las casillas.");
            
        }else if (!edadvalida(jd_fecha.getDate())) {
            jL_edad.setVisible(true);
        } else {
            usuarios.add(new Usuario(jTF_nombre.getText(),
                                    jTF_correo.getText(),
                                    jTF_pais.getText(),"","",150000,
                                    jd_fecha.getDate())
            );
            jTF_nombre.setText("");
            jTF_correo.setText("");
            jTF_pais.setText("");
            jd_fecha.setDate(new Date());
            jL_edad.setVisible(false);
            
            jP_CrearCuenta.setVisible(false);
            jP_IniciarSesion.setVisible(false);
            jL_contra.setVisible(false);
            jL_contra2.setVisible(false);
            jP_Dentro.setVisible(false);
            jP_Garage.setVisible(false);
            jP_Concesionaria.setVisible(false);
            jP_VentaCarros.setVisible(false);
            jP_CrearUsuario.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()==27) {
            jD_Menu.setVisible(true);
            jD_Menu.pack();
            jD_Menu.setLocationRelativeTo(this);
        }
    }//GEN-LAST:event_formKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (jTF_usuario.getText().isEmpty() || jPF_Password.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Llene las casillas.");
        }else if (!validarContra(jPF_Password.getText())) {
            jL_contra.setVisible(true);
            jL_contra2.setVisible(true); 
            jTF_usuario.setText("");
            jPF_Password.setText("");
        }else{
            usuarios.add(new Usuario(jTF_nombre.getText(),
                                    jTF_correo.getText(),
                                    jTF_pais.getText(),jTF_usuario.getText(),jPF_Password.getText(),150000,
                                    jd_fecha.getDate())
            );
            JOptionPane.showMessageDialog(this, "Usuario creado existosamente");
            jP_CrearCuenta.setVisible(false);
            jP_CrearUsuario.setVisible(false);
            jP_IniciarSesion.setVisible(false);
            jP_Dentro.setVisible(false);
            jP_Concesionaria.setVisible(false);
            jP_Garage.setVisible(false);
            jP_VentaCarros.setVisible(false);
            jB_login.setVisible(true);
            jB_crear.setVisible(true);
            jL_Iniciar.setVisible(true);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jB_crearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_crearMouseClicked
        // TODO add your handling code here:
        jL_edad.setVisible(false);
        jL_Iniciar.setVisible(false);
        jP_IniciarSesion.setVisible(false);
        jP_CrearUsuario.setVisible(false);
        jB_login.setVisible(false);
        jB_crear.setVisible(false);
        jP_Dentro.setVisible(false);
        jP_Concesionaria.setVisible(false);
        jP_Garage.setVisible(false);
        jP_VentaCarros.setVisible(false);
        jP_CrearCuenta.setVisible(true);
    }//GEN-LAST:event_jB_crearMouseClicked

    private void jB_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jB_loginMouseClicked
        // TODO add your handling code here:
        jL_Iniciar.setVisible(false);
        jP_CrearUsuario.setVisible(false);
        jP_CrearCuenta.setVisible(false);
        jB_login.setVisible(false);
        jB_crear.setVisible(false);
        jP_VentaCarros.setVisible(false);
        jP_IniciarSesion.setVisible(true);
    }//GEN-LAST:event_jB_loginMouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        jL_Iniciar.setVisible(false);
        jP_IniciarSesion.setVisible(false);
        jP_CrearUsuario.setVisible(false);
        jB_login.setVisible(false);
        jB_crear.setVisible(false);
        jP_Dentro.setVisible(false);
        jP_CrearCuenta.setVisible(false);
        jP_Concesionaria.setVisible(true);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jCB_Carros_paisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCB_Carros_paisItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            String paisSeleccionado = (String) jCB_Carros_pais.getSelectedItem();

            DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
            modelo.setRowCount(0);

            for (Carro car : carros) {
                if (car.getPais().equals(paisSeleccionado)) {
                    Object[] newrow = {
                        car.getMarca(),
                        car.getModelo(),
                        car.getYear(),
                        car.getPrecio()
                    };
                    modelo.addRow(newrow);
                }
            }
        }
    }//GEN-LAST:event_jCB_Carros_paisItemStateChanged

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        if (jTF_usuarioInicio.getText().isEmpty() || jPF_PasswordInicio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Llene las casillas.");  
        }else{
            boolean siesta=false;
            for (Usuario usuario : usuarios) {
                if (usuario.getUsuario().equals(jTF_usuarioInicio.getText()) && usuario.getPassword().equals(jPF_PasswordInicio.getText())) {
                   JOptionPane.showMessageDialog(this, "Bienvenido!!");
                   usuarioEnSesion = usuario; 
                   siesta=true;
                   break;
                }
            }
            if (siesta) {
                jL_Iniciar.setVisible(false);
                jP_IniciarSesion.setVisible(false);
                jP_CrearUsuario.setVisible(false);
                jP_CrearCuenta.setVisible(false);
                jB_login.setVisible(false);
                jB_crear.setVisible(false);
                jP_Concesionaria.setVisible(false);
                jP_Garage.setVisible(false);
                jP_VentaCarros.setVisible(false);
                jP_Dentro.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos.");
            }
        }
    }//GEN-LAST:event_jButton7MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            //seleccionar un nodo con click derecho
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jL_Iniciar.setVisible(false);
        jP_IniciarSesion.setVisible(false);
        jP_CrearUsuario.setVisible(false);
        jP_CrearCuenta.setVisible(false);
        jB_login.setVisible(false);
        jB_crear.setVisible(false);
        jP_VentaCarros.setVisible(false);
        jP_Dentro.setVisible(false);
        jP_Garage.setVisible(false);
        jP_Concesionaria.setVisible(true);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            String paisSeleccionado = (String) jComboBox1.getSelectedItem();

            DefaultTableModel modelo = (DefaultTableModel) jTable2.getModel();
            modelo.setRowCount(0);

            ArrayList<Carro> carrosUsuario = usuarioEnSesion.getCarros();
            for (Carro car : carrosUsuario) {
                if (car.getPais().equals(paisSeleccionado)) {
                    Object[] newrow = {
                        car.getMarca(),
                        car.getModelo(),
                        car.getYear(),
                        car.getPrecio()
                    };
                    modelo.addRow(newrow);
                }
            }
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jL_Iniciar.setVisible(false);
        jP_IniciarSesion.setVisible(false);
        jP_CrearUsuario.setVisible(false);
        jP_CrearCuenta.setVisible(false);
        jB_login.setVisible(false);
        jB_crear.setVisible(false);
        jP_Concesionaria.setVisible(false);
        jP_Dentro.setVisible(false);
        jP_Garage.setVisible(false);
        jP_VentaCarros.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jL_Iniciar.setVisible(false);
        jP_IniciarSesion.setVisible(false);
        jP_CrearUsuario.setVisible(false);
        jP_CrearCuenta.setVisible(false);
        jB_login.setVisible(false);
        jB_crear.setVisible(false);
        jP_Concesionaria.setVisible(false);
        jP_VentaCarros.setVisible(false);
        jP_Dentro.setVisible(false);
        jP_Garage.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        
        int selectedRow = jTable2.getSelectedRow();
        if (selectedRow >= 0) {
            Carro selectedCar = obtenerCarroDesdeFila(selectedRow);
            actualizarJListMejoras(selectedCar);
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton18MouseClicked
        // TODO add your handling code here:
        VolverIncio();
    }//GEN-LAST:event_jButton18MouseClicked

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        VolverIncio();
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton19MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19MouseClicked

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    public static boolean edadvalida(Date fecha) {
        Date fechaActual = new Date();
        long edad = fechaActual.getTime() - fecha.getTime();
        long edadActual = edad / (1000L * 60 * 60 * 24 * 365);
        return edadActual >= 12;
    }
    
    private boolean validarContra(String password) {
        boolean mayus = false, 
                minus = false, 
                caracterEspecial = false;

        for (char caracter : password.toCharArray()) {
            if (Character.isUpperCase(caracter)) {
                mayus = true;
            } else if (Character.isLowerCase(caracter)) {
                minus = true;
            } else if (!Character.isLetterOrDigit(caracter)) {
                caracterEspecial = true;
            }
        }

        return mayus && minus && caracterEspecial;
    }
    
    private Carro obtenerCarroDesdeFila(int fila) {
        String marca = jTable2.getValueAt(fila, 0).toString();
        String modelo = jTable2.getValueAt(fila, 1).toString();

        for (Carro carro : carros) {
            if (carro.getMarca().equals(marca) && carro.getModelo().equals(modelo)) {
                return carro;
            }
        }

        return null;
    }
    private void actualizarJListMejoras(Carro carro) {
        DefaultListModel modelo = new DefaultListModel();

        ArrayList<String> mejorasVisuales = carro.getMejorasVisuales();

        for (String mejora : mejorasVisuales) {
            modelo.addElement(mejora);
        }
        jListMejoras.setModel(modelo);
    }
    
    public void VolverIncio() {
        jP_IniciarSesion.setVisible(false);
        jP_CrearCuenta.setVisible(false);
        jP_CrearUsuario.setVisible(false);
        jP_Concesionaria.setVisible(false);
        jP_Dentro.setVisible(false);
        jP_Garage.setVisible(false);
        jP_VentaCarros.setVisible(false);
        jL_Iniciar.setVisible(true);
        jB_login.setVisible(true);
        jB_crear.setVisible(true);
    }
    
    /*private void carrosAgrgar() {
        carros.add(new Carro("Subaru", "WR-X", Color.BLACK, 100, null, "Japón", 2022, false));
        carros.add(new Carro("Subaru", "Imprez", Color.BLACK, 100, null, "Japón", 2022, false));
        carros.add(new Carro("Subaru", "BRZ", Color.BLACK, 100, null, "Japón", 2022, false));
        carros.add(new Carro("Toyota", "GT-86", Color.BLACK, 100, null, "Japón", 2022, false));
        carros.add(new Carro("Toyota", "Supra", Color.BLACK, 100, null, "Japón", 2022, false));
        carros.add(new Carro("Honda", "Integra type-R", Color.BLACK, 100, null, "Japón", 2022, false));
        carros.add(new Carro("Honda", "CR-X", Color.BLACK, 100, null, "Japón", 2022, false));
        carros.add(new Carro("Mitsubishi", "Lancer Evo", Color.BLACK, 100, null, "Japón", 2022, false));
        carros.add(new Carro("Mitsubishi", "Mirage", Color.BLACK, 100, null, "Japón", 2022, false));
        carros.add(new Carro("Nisan", "CR-X", Color.BLACK, 100, null, "Japón", 2022, false));
        
        carros.add(new Carro("Ford", "Mustang", Color.BLACK, 100, null, "USA", 2022, false));
        carros.add(new Carro("Ford", "F-150", Color.BLACK, 100, null, "USA", 2022, false));
        carros.add(new Carro("Chevloret", "Camaro", Color.BLACK, 100, null, "USA", 2022, false));
        carros.add(new Carro("Chevloret", "Corvette", Color.BLACK, 100, null, "USA", 2022, false));
        carros.add(new Carro("Chevloret", "Bel-Hir", Color.BLACK, 100, null, "USA", 2022, true));
        
        carros.add(new Carro("BWW", "M3", Color.BLACK, 100, null, "Alemania", 2022, false));
        carros.add(new Carro("BWW", "X6", Color.BLACK, 100, null, "Alemania", 2022, false));
        carros.add(new Carro("BWW", "M5", Color.BLACK, 100, null, "Alemania", 2022, false));
        carros.add(new Carro("Mercedes", "", Color.BLACK, 100, null, "Alemania", 2022, false));
        carros.add(new Carro("XW", "Beetle", Color.BLACK, 100, null, "Alemania", 2022, false));
        carros.add(new Carro("XW", "Nordon Concept", Color.BLACK, 100, null, "Alemania", 2022, false));
        carros.add(new Carro("Audi", "R8", Color.BLACK, 100, null, "Alemania", 2022, false));
        carros.add(new Carro("Audi", " T= Coupe", Color.BLACK, 100, null, "Alemania", 2022, false));
        
        carros.add(new Carro("Peugeot", "206", Color.BLACK, 100, null, "Francia", 2022, false));
        
        carros.add(new Carro("Mini", "Mini", Color.BLACK, 100, null, "UK", 2022, false));
        carros.add(new Carro("Mini", "Countryman", Color.BLACK, 100, null, "UK", 2022, false));
        
        carros.add(new Carro("Volvo", "", Color.BLACK, 100, null, "Suecia", 2022, false));
    }*/
    
    private ArrayList<Usuario> usuarios= new ArrayList();
    private ArrayList<Carro> carros= new ArrayList();
    private Usuario usuarioEnSesion;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_crear;
    private javax.swing.JButton jB_login;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jCB_Carros_pais;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDialog jD_Menu;
    private javax.swing.JLabel jL_Iniciar;
    private javax.swing.JLabel jL_contra;
    private javax.swing.JLabel jL_contra2;
    private javax.swing.JLabel jL_edad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jListMejoras;
    private javax.swing.JMenuItem jMenuItem_Eliminar;
    private javax.swing.JMenuItem jMenuItem_Marca;
    private javax.swing.JMenuItem jMenuItem_Modelo;
    private javax.swing.JMenuItem jMenuItem_precio;
    private javax.swing.JMenuItem jMenuItem_year;
    private javax.swing.JMenu jMenu_modificar;
    private javax.swing.JPasswordField jPF_Password;
    private javax.swing.JPasswordField jPF_PasswordInicio;
    private javax.swing.JPanel jP_Concesionaria;
    private javax.swing.JPanel jP_CrearCuenta;
    private javax.swing.JPanel jP_CrearUsuario;
    private javax.swing.JPanel jP_Dentro;
    private javax.swing.JPanel jP_Garage;
    private javax.swing.JPanel jP_IniciarSesion;
    private javax.swing.JPanel jP_Inicio;
    private javax.swing.JPanel jP_VentaCarros;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTF_correo;
    private javax.swing.JTextField jTF_nombre;
    private javax.swing.JTextField jTF_pais;
    private javax.swing.JTextField jTF_usuario;
    private javax.swing.JTextField jTF_usuarioInicio;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private com.toedter.calendar.JDateChooser jd_fecha;
    // End of variables declaration//GEN-END:variables
}
